### PR TITLE
Split Conv2d to Conv2d and ConvTranspose2d

### PR DESCRIPTION
**Pull request by Honry**
Rebase to webnn-native latest commit as well.

Commit id: 0d5517e45532f5950a5ffddd316570032d58841f

### CODE REVIEW

**Comment by Honry** [comment]
@huningxin, PTAL, thanks!

**Comment by huningxin** [comment]
@Honry , thanks. Code LGTM. My question is whether we should merge it into the webnn_delegate branch first?

**Comment by Honry** [comment]
I'm OK to merge it into webnn_delegate branch first, thus we could start rebasing webnn-native in old emscripten and tflite-support.

**Comment by huningxin** [comment]
@Honry , you are right.

webnn-delegate-tfjs-tflite-node is for node usage which has less dependency. 

webnn_delegate branch is more for wasm usage which depends on emscripten and tflite-support.

I am fine to merge it to this branch and work on webnn_delegate for wasm usage later.

Thanks!

**Review by huningxin — APPROVED** [review]
LGTM.

**Pull request merged**
