### PR TITLE
Support Split, FullyConnected, Tanh, Sigmoid, Unpack ops

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@huningxin, PTAL, for FullyConnected, if the rank of input greater than 2, the WebNN will core dump. I haven't found the root cause yet. And the model from codelab works, as it only has 2D input for FullyConnected.

>wm@wm:~/work/webml/webnn/frameworks/tensorflow/tensorflow$ bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model   --graph=/home/wm/Downloads/meet_denoiser_par_lstm_float.tflite   --external_delegate_path=./bazel-bin/tensorflow/lite/delegates/webnn/libwebnn_external_delegate_obj.so --num_runs=101 --external_delegate_options='webnn_device:0'
STARTING!
Log parameter values verbosely: [0]
Min num runs: [101]
Graph: [/home/wm/Downloads/meet_denoiser_par_lstm_float.tflite]
External delegate path: [./bazel-bin/tensorflow/lite/delegates/webnn/libwebnn_external_delegate_obj.so]
External delegate options: [webnn_device:0]
Loaded model /home/wm/Downloads/meet_denoiser_par_lstm_float.tflite
WebNN delegate: WebNN device set to 0.
INFO: Created TensorFlow Lite WebNN delegate for device Default and power Default.
Explicitly applied EXTERNAL delegate, and the model graph will be partially executed by the delegate w/ 5 delegate kernels.
The input model file size (MB): 12.2262
Initialized session in 94.758ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
Segmentation fault (core dumped)

**Comment by huningxin** [comment]
Thanks @Honry .

> for FullyConnected, if the rank of input greater than 2, the WebNN will core dump. I haven't found the root cause yet. And the model from codelab works, as it only has 2D input for FullyConnected.

Great progress on codelab model.

I didn't see any issues in your fully connected impl. Are you sure it crashes at fully connected or other op of the model under your test? Did you happen to debug it?

**Comment by Honry** [comment]
> I didn't see any issues in your fully connected impl. Are you sure it crashes at fully connected or other op of the model under your test? Did you happen to debug it?

Removing the fully connected from delegate, the denoising model works. I didn't debug deeply, as it crashed at webnn-native and may take long time. I think we can make it lower priority, as it doesn't block codelab model.

**Comment by huningxin** [comment]
> I think we can make it lower priority, as it doesn't block codelab model.

As it is a crash issue and impacts denoising model, I think its priority is not low. But I agree with you it doesn't block codelab model.

> I didn't debug deeply, as it crashed at webnn-native and may take long time.

@miaobin, could you please help debug the webnn-native side?

**Review by huningxin — APPROVED** [review]
Let's merge it to unblock the codelab work.

**Pull request merged**
